# Generated by Django 2.2.19 on 2022-06-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название группы')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(verbose_name='Описание группы')),
            ],
        ),
    ]
